blog/urls.py
from django.urls import path
from .views import render_posts, post_detail
app_name = "blog"
urlpatterns = [
    path('',render_posts, name='posts'),
    path("<int:post_id>", post_detail,
        name="post_detail")
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/', include('blog.urls'))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
#Modelo de blog
class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField
class Project(models.Model):
    titele = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images')
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
#Vista de blog
def render_posts(request): #Primera vista del blog 
    articulos = Post.objects.all()
    return render(request, 'posts.html', {'posts':articulos})
def post_detail(request, post_id): #Vista del blog parte de los detalles
    post = get_object_or_404(Post, pk=post_id)
    #El metodo render pide el nombre de la plantilla
    return render(request, 'post_detail.html', {"post":post})

portfolio/views.py
from django.shortcuts import render
from .models import Project
def home(request): #Primera vista de la pagina principal
    projects = Project.objects.all()
    return render(request, 'home.html',{'projects': projects})

blog/templates/post_detail.html
<!--Hereda de la barra de plantilla principal de layout.html-->
{% extends 'layout.html' %}
{% block content %}
<div class="text-center">
    <h1>{{post.title}}</h1>
    <h2 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h2>
    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
    <div class="my-4">
    {{post.description|safe}}
    </div>
  </div>
{% endblock %}

blog/templates/posts.html
<!--Hereda de la barra de plantilla principal de layout.html-->
{% extends 'layout.html' %}
{% block content %}
<!--El mensaje principal del blog-->
<h1 >Publicaciones</h1>
<!-- {{total_posts}} post{{total_posts|pluralize}}-->
<h3>Hay publicaciones sobre:</h3>
{% for post in posts %}
<div class="py-3">
    <div class="card card-body bg-black">
      <div class="row">
        <div class="col-3">
          <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">
        </div>
        <div class="col-9">
          <h1>{{post.title}}</h1>
          <p>{{post.description|striptags|truncatechars:100}}</p>
          <p>{{post.date|date:'M d Y'|upper}}</p>
            <!--Poder cambiar el para entrar en detalles-->
          <a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
{% endblock %}

portfolio/templates/home.html
<!--Hereda de la barra de plantilla principal de navbar.html-->
{% extends 'layout.html' %}
<!--Significa que este contenido puede cambiar-->
{% block content %}
{% load static %}
<header class="row bg-black">
    <div class="col-md-4">
        <!--La ubicacion del la imagen-->
        <img src="{% static 'portfolio/perfil.jpg' %}" alt="" width="200" height="265">
    </div>
    <div class="col-md-8 my-auto">
        <h1>Yo soy <strong>Joel Cedeño</strong></h1>
        <h3>Desarrollador Web</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga fugit temporibus dolorem veniam
            vitae consectetur voluptate possimus itaque! Possimus ullam tempora deleniti iure aliquid sequi,
            ipsam minus quibusdam odit natus!</p>
        <!--La ubicacion del pdf-->
        <!--Nombre de la descarga de la portada para el curriculo-->
        <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'portfolio/curriculum.pdf' %}" target="_blank">
                Descargar</a>
    </div>
</header>
<!--Centrar las targetas-->
<div class="row my-4 text-center">
  <!--Aqui comienza la configuracion del proyecto-->
  <h1>Mis proyectos</h1>
  <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
  {% for project in projects %}
  <div class="col-md-4 p-4">
    <div class="card bg-black card-project">
      <!--Cambia la presentacion del los proyectos img-fluid-->
      <img src="{{project.image.url }}" class="card-img-top" />
      <div class="card-body">
        <h2>{{ project.title }}</h2>
        <p>{{ project.description }}</p>
        {% if project.url %}
        <!--El link donde manda a mi git-hub-->
        <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="__blank" rel="noreferrer">
          Visitar mi proyecto</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
    {% endblock %}
  </div>
  

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pagina Principal</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
    crossorigin="anonymous">
    <!--La ubicacion del archivo css-->
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">
    {% include 'partials/navbar.html' %}
    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<!--La barra de navegacion de la pagina web todo este código-->
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <!--Nombre de la persona-->
    <a class="navbar-brand fw-bold fst-italic" href="/">Joel Cedeño</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <!--Nombre de la descarga del menu para el curriculo-->
          <a class="btn btn-primary btn-sm" href="{% static 'portfolio/curriculum.pdf' %}" target="_blank">Descargar</a>
        </li>
      </ul>
    </div>
  </div>
</nav>